# Site settings
title: Awesome Site Title
email: your-email@domain.com
description: >
  Awesome site description here
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arabic-droid.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage



facebook_admin:
facebook_id:
twitter_username:
facebook_profile:


name: 'Your Name'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
