# Site settings
title: Awesome Site Title
description: >
  Awesome site description here
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arabic-droid.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage


author:
email: your-email@domain.com
disqus_name:
facebook_admin:
facebook_id:
twitter_username:
facebook_profile:
google_analytics: ""


author_bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"


# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
